"""adicionar itens aos pedidos

Revision ID: 89b1c6cf1693
Revises: 52cdd8a69416
Create Date: 2026-09-17 16:42:54.096175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89b1c6cf1693'
down_revision: Union[str, Sequence[str], None] = '52cdd8a69416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('itens_pedido', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('usuarios', 'senha',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'usuarios', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.alter_column('usuarios', 'senha',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('itens_pedido', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
